//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfInvokeDemo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/WcfInvokeDemo")]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private int AgeField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPersonService")]
public interface IPersonService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPersonName", ReplyAction="http://tempuri.org/IPersonService/GetPersonNameResponse")]
    string GetPersonName(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPersonName", ReplyAction="http://tempuri.org/IPersonService/GetPersonNameResponse")]
    System.Threading.Tasks.Task<string> GetPersonNameAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPerson", ReplyAction="http://tempuri.org/IPersonService/GetPersonResponse")]
    WcfInvokeDemo.Person GetPerson(WcfInvokeDemo.Person person);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetPerson", ReplyAction="http://tempuri.org/IPersonService/GetPersonResponse")]
    System.Threading.Tasks.Task<WcfInvokeDemo.Person> GetPersonAsync(WcfInvokeDemo.Person person);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPersonServiceChannel : IPersonService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PersonServiceClient : System.ServiceModel.ClientBase<IPersonService>, IPersonService
{
    
    public PersonServiceClient()
    {
    }
    
    public PersonServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetPersonName(string name)
    {
        return base.Channel.GetPersonName(name);
    }
    
    public System.Threading.Tasks.Task<string> GetPersonNameAsync(string name)
    {
        return base.Channel.GetPersonNameAsync(name);
    }
    
    public WcfInvokeDemo.Person GetPerson(WcfInvokeDemo.Person person)
    {
        return base.Channel.GetPerson(person);
    }
    
    public System.Threading.Tasks.Task<WcfInvokeDemo.Person> GetPersonAsync(WcfInvokeDemo.Person person)
    {
        return base.Channel.GetPersonAsync(person);
    }
}
